// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIHlnR9bzLUCPdtLq8KsYgyCErK5YTsx8',
    appId: '1:311651151968:web:ebe6303796352acd501305',
    messagingSenderId: '311651151968',
    projectId: 'acehacks-9d5f1',
    authDomain: 'acehacks-9d5f1.firebaseapp.com',
    storageBucket: 'acehacks-9d5f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRTeNU3sPH41ZYLHYt65cAGgWCda56G98',
    appId: '1:311651151968:android:dfbefa00482235f8501305',
    messagingSenderId: '311651151968',
    projectId: 'acehacks-9d5f1',
    storageBucket: 'acehacks-9d5f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlynfBdZfVM8pq0Q-H-7x2mVsCYpjX0tI',
    appId: '1:311651151968:ios:a3477ca4ba4c1476501305',
    messagingSenderId: '311651151968',
    projectId: 'acehacks-9d5f1',
    storageBucket: 'acehacks-9d5f1.appspot.com',
    iosBundleId: 'com.example.ace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlynfBdZfVM8pq0Q-H-7x2mVsCYpjX0tI',
    appId: '1:311651151968:ios:7c87e1d135ddfbfb501305',
    messagingSenderId: '311651151968',
    projectId: 'acehacks-9d5f1',
    storageBucket: 'acehacks-9d5f1.appspot.com',
    iosBundleId: 'com.example.ace.RunnerTests',
  );
}
